### ISSUE TITLE
Routes tree?

### ISSUE THREAD

**Issue by jacomyal** [jacomyal/baobab-router#8]
It might be useful to deal with the routes as a tree similarly to react-router.

**Comment by gersongoulart** [comment]
+1 I would be really nice to have the routes defined as part of the state of the app. This way state history would also keep track of navigation/url state

**Comment by jacomyal** [comment]
Hi @gersongoulart,

Since baobab-router uses two-way bindings, it will probably pollute your state history, since some features are dealt by updating the state, then the URL, etc...

For instance, if the state does not match any existing route, then it will fallback to the default route URL, which will trigger a state update. Basically, I want to use baobab-router to apply some constraints on my app state, and this will certainly trigger many "unwanted" tree updates.

Anyway, I just pushed the [routes-tree](https://github.com/jacomyal/baobab-router/tree/routes-tree) branch today, with a draft of what might become the v1.

The [README](https://github.com/jacomyal/baobab-router/blob/routes-tree/README.md) just describes a basic use case, but the [collection.advanced.js](https://github.com/jacomyal/baobab-router/blob/routes-tree/test/collection.advanced.js) contains a more advanced example. I am right now commenting it more accurately in the README.

It is not yet to be released, since I'd like to have some feedbacks about the new features.

**Comment by jacomyal** [comment]
**The *routes-tree* branch no longer exists, it is now all merged in master.**
