### ISSUE TITLE
Implementation Examples

### ISSUE THREAD

**Issue by gersongoulart** [jacomyal/baobab-router#9]
It would be nice to have some examples of how to implement this router with popular libraries. For example, I'm currently trying to use it with React but not sure how to mount components based on baobab-router state changes...

**Comment by Yomguithereal** [comment]
baobab-router binds the url changes to a baobab tree. This means that if the url changes, so does the baobab tree and, the other way around, if the baobab tree catch relevant changes, it will update the url.

So there are really no differences between using the boabab cursors/data and use them inside a React component and what baobab-router proposes.

*Example*

```jsx
var tree = new Baobab({
  view: 'home'
});

var router = new BaobabRouter(tree, [
  {
    route: '/home',
    defaultRoute: true,
    state: {
      view: 'home'
    }
  },
  {
    route: '/settings',
    state: {
      view: 'settings'
    }
  }
]);

var Navigation = React.createClass({
  cursor: ['view'],
  render: function() {
    var currentView = this.cursor.get();

    return (
      <ul>
        <li><a className={currentView === 'home' ? 'active' : ''} href="#/home">Home</a></li>
        <li><a className={currentView === 'settings' ? 'active' : ''}href="#/settings">Settings</a></li>
      </ul>
    );
  }
});
```

We will produce better examples in the future with @jacomyal when we can find some time.

**Comment by Yomguithereal** [comment]
As a side note: I tried to use both `react-router` and `baobab` once and found that this can work but only if you application's state does not need to know anything about the url (sometimes, it is impossible but in a lot of case, considering the router and the state tree as two different stores can make sense).

This library was therefore created by @jacomyal for cases when your application's state effectively relies on the current url fragments.

**Comment by jacomyal** [comment]
The [README](https://github.com/jacomyal/baobab-router/blob/master/README.md) now provides two different examples. Though, these examples just show the interactions between the URL and the state, and do not go as far as showing some views examples.
